from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 450)
        self.usernameLabel = QtWidgets.QLabel(Form)
        self.usernameLabel.setGeometry(QtCore.QRect(40, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(Form)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.ageLabel = QtWidgets.QLabel(Form)
        self.ageLabel.setGeometry(QtCore.QRect(40, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.genderLabel = QtWidgets.QLabel(Form)
        self.genderLabel.setGeometry(QtCore.QRect(40, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.countryLabel = QtWidgets.QLabel(Form)
        self.countryLabel.setGeometry(QtCore.QRect(40, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.countryLabel.setFont(font)
        self.countryLabel.setObjectName("countryLabel")
        self.phoneLabel = QtWidgets.QLabel(Form)
        self.phoneLabel.setGeometry(QtCore.QRect(40, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setObjectName("phoneLabel")
        self.usernameEdit = QtWidgets.QLineEdit(Form)
        self.usernameEdit.setGeometry(QtCore.QRect(170, 70, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.usernameEdit.setFont(font)
        self.usernameEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usernameEdit.setObjectName("usernameEdit")
        self.passwordEdit = QtWidgets.QLineEdit(Form)
        self.passwordEdit.setGeometry(QtCore.QRect(170, 120, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setMaxLength(4)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordEdit.setObjectName("passwordEdit")
        self.phoneEdit = QtWidgets.QLineEdit(Form)
        self.phoneEdit.setGeometry(QtCore.QRect(170, 320, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.phoneEdit.setFont(font)
        self.phoneEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.phoneEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.phoneEdit.setObjectName("phoneEdit")
        self.ageBox = QtWidgets.QSpinBox(Form)
        self.ageBox.setGeometry(QtCore.QRect(170, 170, 42, 22))
        self.ageBox.setMinimum(10)
        self.ageBox.setMaximum(100)
        self.ageBox.setObjectName("ageBox")
        self.maleRadioBtn = QtWidgets.QRadioButton(Form)
        self.maleRadioBtn.setGeometry(QtCore.QRect(170, 220, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.maleRadioBtn.setFont(font)
        self.maleRadioBtn.setChecked(False)
        self.maleRadioBtn.setObjectName("maleRadioBtn")
        self.femaleRadioBtn = QtWidgets.QRadioButton(Form)
        self.femaleRadioBtn.setGeometry(QtCore.QRect(250, 220, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.femaleRadioBtn.setFont(font)
        self.femaleRadioBtn.setChecked(True)
        self.femaleRadioBtn.setObjectName("femaleRadioBtn")
        self.countryCombo = QtWidgets.QComboBox(Form)
        self.countryCombo.setGeometry(QtCore.QRect(170, 270, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.countryCombo.setFont(font)
        self.countryCombo.setEditable(True)
        self.countryCombo.setObjectName("countryCombo")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.clearBtn = QtWidgets.QPushButton(Form)
        self.clearBtn.setGeometry(QtCore.QRect(40, 380, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        self.clearBtn.setStyleSheet( "QPushButton::hover"
                     "{"
                     "background-color : lightgrey;"
                     "}")
        
        self.enterBtn = QtWidgets.QPushButton(Form)
        self.enterBtn.setGeometry(QtCore.QRect(230, 380, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.enterBtn.setFont(font)
        self.enterBtn.setObjectName("enterBtn")
        self.enterBtn.setStyleSheet( "QPushButton::hover"
                     "{"
                     "background-color : lightgrey;"
                     "}")
        


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.usernameLabel.setText(_translate("Form", "Username : "))
        self.passwordLabel.setText(_translate("Form", "Password : "))
        self.ageLabel.setText(_translate("Form", "Age :"))
        self.genderLabel.setText(_translate("Form", "Gender : "))
        self.countryLabel.setText(_translate("Form", "Country :"))
        self.phoneLabel.setText(_translate("Form", "Phone :"))
        self.maleRadioBtn.setText(_translate("Form", "Male"))
        self.femaleRadioBtn.setText(_translate("Form", "Female"))
        self.countryCombo.setItemText(0, _translate("Form", "Uzbekistan"))
        self.countryCombo.setItemText(1, _translate("Form", "Russia"))
        self.countryCombo.setItemText(2, _translate("Form", "America"))
        self.countryCombo.setItemText(3, _translate("Form", "China"))
        self.countryCombo.setItemText(4, _translate("Form", "Canada"))
        self.clearBtn.setText(_translate("Form", "Clear"))
        self.enterBtn.setText(_translate("Form", "Enter"))

        self.clearBtn.clicked.connect(self.clear)
        self.enterBtn.clicked.connect(self.enter)



    def clear(self):
        self.usernameEdit.clear()
        self.passwordEdit.clear()
        self.countryCombo.clear()
        self.ageBox.clear()
        self.phoneEdit.clear()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    app.exec_()
    